from ultralytics import YOLO
import numpy as np

YOLO_CLASSES = {
    0: "Accessory Gift Set",
    1: "Baby Dolls",
    2: "Backpacks",
    3: "Bangle",
    4: "Basketballs",
    5: "Bath Robe",
    6: "Beauty Accessory",
    7: "Belts",
    8: "Blazers",
    9: "Body Lotion",
    10: "Body Wash and Scrub",
    11: "Booties",
    12: "Boxers",
    13: "Bra",
    14: "Bracelet",
    15: "Briefs",
    16: "Camisoles",
    17: "Capris",
    18: "Caps",
    19: "Casual Shoes",
    20: "Churidar",
    21: "Clothing Set",
    22: "Clutches",
    23: "Compact",
    24: "Concealer",
    25: "Cufflinks",
    26: "Cushion Covers",
    27: "Deodorant",
    28: "Dresses",
    29: "Duffel Bag",
    30: "Dupatta",
    31: "Earrings",
    32: "Eye Cream",
    33: "Eyeshadow",
    34: "Face Moisturisers",
    35: "Face Scrub and Exfoliator",
    36: "Face Serum and Gel",
    37: "Face Wash and Cleanser",
    38: "Flats",
    39: "Flip Flops",
    40: "Footballs",
    41: "Formal Shoes",
    42: "Foundation and Primer",
    43: "Fragrance Gift Set",
    44: "Free Gifts",
    45: "Gloves",
    46: "Hair Accessory",
    47: "Hair Colour",
    48: "Handbags",
    49: "Hat",
    50: "Headband",
    51: "Heels",
    52: "Highlighter and Blush",
    53: "Innerwear Vests",
    54: "Ipad",
    55: "Jackets",
    56: "Jeans",
    57: "Jeggings",
    58: "Jewellery Set",
    59: "Jumpsuit",
    60: "Kajal and Eyeliner",
    61: "Key chain",
    62: "Kurta Sets",
    63: "Kurtas",
    64: "Kurtis",
    65: "Laptop Bag",
    66: "Leggings",
    67: "Lehenga Choli",
    68: "Lip Care",
    69: "Lip Gloss",
    70: "Lip Liner",
    71: "Lip Plumper",
    72: "Lipstick",
    73: "Lounge Pants",
    74: "Lounge Shorts",
    75: "Lounge Tshirts",
    76: "Makeup Remover",
    77: "Mascara",
    78: "Mask and Peel",
    79: "Mens Grooming Kit",
    80: "Messenger Bag",
    81: "Mobile Pouch",
    82: "Mufflers",
    83: "Nail Essentials",
    84: "Nail Polish",
    85: "Necklace and Chains",
    86: "Nehru Jackets",
    87: "Night suits",
    88: "Nightdress",
    89: "Patiala",
    90: "Pendant",
    91: "Perfume and Body Mist",
    92: "Rain Jacket",
    93: "Rain Trousers",
    94: "Ring",
    95: "Robe",
    96: "Rompers",
    97: "Rucksacks",
    98: "Salwar",
    99: "Salwar and Dupatta",
    100: "Sandals",
    101: "Sarees",
    102: "Scarves",
    103: "Shapewear",
    104: "Shirts",
    105: "Shoe Accessories",
    106: "Shoe Laces",
    107: "Shorts",
    108: "Shrug",
    109: "Skirts",
    110: "Socks",
    111: "Sports Sandals",
    112: "Sports Shoes",
    113: "Stockings",
    114: "Stoles",
    115: "Sunglasses",
    116: "Sunscreen",
    117: "Suspenders",
    118: "Sweaters",
    119: "Sweatshirts",
    120: "Swimwear",
    121: "Tablet Sleeve",
    122: "Ties",
    123: "Ties and Cufflinks",
    124: "Tights",
    125: "Toner",
    126: "Tops",
    127: "Track Pants",
    128: "Tracksuits",
    129: "Travel Accessory",
    130: "Trolley Bag",
    131: "Trousers",
    132: "Trunk",
    133: "Tshirts",
    134: "Tunics",
    135: "Umbrellas",
    136: "Waist Pouch",
    137: "Waistcoat",
    138: "Wallets",
    139: "Watches",
    140: "Water Bottle",
    141: "Wristbands"
}

class YoloModel:

    def __init__(self, weights_path: str):
        self.model = YOLO(model=weights_path, task="classify")

    def predict(self, image: str | np.ndarray | list) -> tuple[str, float]:
        results = self.model.predict(image, verbose=False, imgsz=128)
        result, = results

        top1_val = result.probs.top1
        top1_str = YOLO_CLASSES[int(result.names[int(top1_val)])]

        return top1_str, result.probs.top1conf
